services:
  - type: web
    name: myapp-financeiro
    env: docker
    plan: starter
    branch: main
    autoDeploy: true
    disk:
      name: myapp-financeiro-data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: FINANCE_APP_USER
        sync: false
      - key: FINANCE_APP_PASSWORD
        sync: false

